const data = [
	{
		id: 1,
		title: "Mip jel urkoh.",
		description:
			"Efloca fe ero gecjouz fumpevdo fir ziek natselni ocejiv zig el camres ni joovi den pucanofil fi so.Vocisekok nipez nete wiepief ma wilal zuhkef milefo savugi rasi uwawo is gepin iveeni akij mo jisnuw rupoc.",
		price: 144,
		coverImg: "https://unsplash.it/528/706?image=395",
		stats: { ratings: "4.0", reviewCount: 37 },
		location: "Dominican Republic",
		openSpots: 16,
		date: "02 Oct, 2022 - 05 Oct, 2022",
	},
	{
		id: 2,
		title: "Feiwukuh ovo.",
		description:
			"Dahpifbi asipeom lapim nilleror har igki tohtedoc kilwuk ti pofi keol rivere lebo guzzi ineirdi fipofi powi zi.Gute vovse toni hubgoc nohi li sek serhig hagev tiho zene fe nesoku jeopepi bunlez tepanop oteumoapi piiko.",
		price: 300,
		coverImg: "https://unsplash.it/528/706?image=927",
		stats: { ratings: "5.1", reviewCount: 133 },
		location: "Japan",
		openSpots: 51,
		date: "11 Feb, 2020 - 14 Feb, 2020",
	},
	{
		id: 3,
		title: "Dogbi anvuv gomo.",
		description:
			"Rovtud vabu ubfi vef ickudij di ruvarvul kozze va zogup paseg pakzolpor ku ejhon gostef ciddu ge ormu.Dihi hafjalcig secke og ofavot goz afufipfi esuse focsu wopce li vetipidip kawnehpes ehmip ze vitwo ro vilgocon.",
		price: 397,
		coverImg: "https://unsplash.it/528/706?image=466",
		stats: { ratings: "5.2", reviewCount: 19 },
		location: "Burundi",
		openSpots: 46,
		date: "08 Jun, 2021 - 14 Jun, 2021",
	},
	{
		id: 4,
		title: "Re zik ijazej.",
		description:
			"Pupaj usja ahitiwre gevdap vemigwe gele azrawfor cusu mear keze mo weuh lita val vogo pibnog culto nos.Rogamu el gag kahiv zorgar ani kieg kohvecen inaruj fotkeoco kokemo jinwehev hophi fobha um torwi soknubu tinoov.",
		price: 301,
		coverImg: "https://unsplash.it/528/706?image=626",
		stats: { ratings: "3.8", reviewCount: 102 },
		location: "Bulgaria",
		openSpots: 58,
		date: "02 Mar, 2015 - 07 Mar, 2015",
	},
	{
		id: 5,
		title: "Ju fufaapu.",
		description:
			"Ekuped minjoh niogireg uv sodatmil pigow fevomvo wi adufe zasodi ri sudsikde zi horhog ewze la ge aj.Nugracir oco dewep sefde tepog wepfa iwu ow tenma pitkirroh givoklum ciwo lianuza ladhob kawfi tov jedgonar joddidla.",
		price: 232,
		coverImg: "https://unsplash.it/528/706?image=7",
		stats: { ratings: "3.2", reviewCount: 45 },
		location: "Gibraltar",
		openSpots: 32,
		date: "14 May, 2016 - 18 May, 2016",
	},
	{
		id: 6,
		title: "Nogenne deszewjuw iwuhe.",
		description:
			"Lecko ge gefro gaf wup zaznaz mav rihpuh ko fogrif doono torpe torros zuc runucjip dih lulopin jenol.Megniw mu rekim uksu agafac kozfehace fivopdo gi damod ocsoftet zo mimet mecit sodoheipa vespobire gitme ovo ehwan.",
		price: 124,
		coverImg: "https://unsplash.it/528/706?image=694",
		stats: { ratings: "5.4", reviewCount: 109 },
		location: "Haiti",
		openSpots: 22,
		date: "15 Jun, 2018 - 17 Jun, 2018",
	},
	{
		id: 7,
		title: "Koohe cej pengeffe.",
		description:
			"Kef cakzap zeine ses cogafemom iskoh loghoaw va gatod lud fojo eneasa togi none vahodonu eke iwsegog gozipe.Ziwgefom tezip ni hi do ogomokwoj maeco olemep zez kefacuhe miok gecov ti tofusni edahu evwapze tizu anupoj.",
		price: 264,
		coverImg: "https://unsplash.it/528/706?image=128",
		stats: { ratings: "5.0", reviewCount: 76 },
		location: "Dominica",
		openSpots: 8,
		date: "01 Oct, 2022 - 03 Oct, 2022",
	},
	{
		id: 8,
		title: "Womejpi nivow imrih.",
		description:
			"Lofrum mewcoz zelfiros eguge igu mupgi zata rovegpeg seli wicninod widis jeoro mijal fupoij vu lecmir zov nimri.Jiw cehgu westu no okazeknuj be depohriv unzo jisalo olto puscipiwi carmeg kado isbav temudop rejic honi nizip.",
		price: 281,
		coverImg: "https://unsplash.it/528/706?image=500",
		stats: { ratings: "2.5", reviewCount: 52 },
		location: "New Caledonia",
		openSpots: 17,
		date: "04 Nov, 2017 - 16 Nov, 2017",
	},
	{
		id: 9,
		title: "Ethud tinkeb.",
		description:
			"Kim vehow cumhe ov madfantes ki eziru juti ta pev toz rumpuor supfev wes kov oksaj sewiwbud noh.Tujzo oca miz wetrohow ru ikketti dosievi wepok pejhujne kejic zimiki eku nirme pececu tuza ulowu sabor oco.",
		price: 251,
		coverImg: "https://unsplash.it/528/706?image=121",
		stats: { ratings: "1.2", reviewCount: 104 },
		location: "Falkland Islands",
		openSpots: 54,
		date: "17 Jun, 2020 - 27 Jun, 2020",
	},
	{
		id: 10,
		title: "Ino gocogow lun.",
		description:
			"Egovap pugis nuoginik ekco woc sur cowi kufiscis fapvur mefow jag sobirij eju lignipo zodiz fowuwe muaf secco.Pikug ibokikvi litcim fijivu vugwoto wi degzik dinviz idvocmu to kuseg ok uc toldo hun lenkohid pusne leohaze.",
		price: 230,
		coverImg: "https://unsplash.it/528/706?image=365",
		stats: { ratings: "4.3", reviewCount: 77 },
		location: "Austria",
		openSpots: 11,
		date: "01 Nov, 2019 - 05 Nov, 2019",
	},
];
export default data;
